// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Category struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
}

type Customer struct {
	CustomerID      string `json:"customer_id"`
	CustomerName    string `json:"customer_name"`
	CustomerAddress string `json:"customer_address"`
	Email           string `json:"email"`
	Password        string `json:"password"`
}

type Product struct {
	ProductID   string    `json:"product_id"`
	CategoryID  int64     `json:"category_id"`
	ProductName string    `json:"product_name"`
	Price       int64     `json:"price"`
	CreatedAt   time.Time `json:"created_at"`
}

type ShoppingCart struct {
	CartID     string    `json:"cart_id"`
	CustomerID string    `json:"customer_id"`
	ProductID  string    `json:"product_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type TransactionReport struct {
	TransactionID string    `json:"transaction_id"`
	CustomerID    string    `json:"customer_id"`
	TotalPrice    int64     `json:"total_price"`
	CreatedAt     time.Time `json:"created_at"`
}
