// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction_report.sql

package db

import (
	"context"
)

const createTransactionReport = `-- name: CreateTransactionReport :one
INSERT INTO transaction_reports (
    transaction_id,
    customer_id,
    total_price
) VALUES (
    $1, $2, $3
) RETURNING transaction_id, customer_id, total_price, created_at
`

type CreateTransactionReportParams struct {
	TransactionID string `json:"transaction_id"`
	CustomerID    string `json:"customer_id"`
	TotalPrice    int64  `json:"total_price"`
}

func (q *Queries) CreateTransactionReport(ctx context.Context, arg CreateTransactionReportParams) (TransactionReport, error) {
	row := q.db.QueryRowContext(ctx, createTransactionReport, arg.TransactionID, arg.CustomerID, arg.TotalPrice)
	var i TransactionReport
	err := row.Scan(
		&i.TransactionID,
		&i.CustomerID,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}
